# Configurations
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            'One inch at a time'
description:      'My journey in software development and beyond'
logo:             /images/me.jpg


# Author Details
author:         'Kingsor'

#Social Media links
linkedin:       'https://www.linkedin.com/in/kingsor'
twitter:        'https://twitter.com/kingsor'
github:         'https://github.com/kingsor'
medium:         'https://medium.com/@kingsor'
twitter_name:	'@kingsor'

# Google Analytics
gahandler: 'UA-3163855-4'

# Blog Configurations
paginate: 5

destination: ./_site

gems:
  - jekyll-sitemap
  - jekyll-paginate

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
  syntax_highlighter: rouge
