# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

# Setup
title:            'One inch at a time'
description:      'My journey in software development and beyond'

# Author Details
author:         'Kingsor'

#Social Media links
linkedin:       'https://www.linkedin.com/in/kingsor'
twitter:        'https://twitter.com/kingsor'
gplus:          'https://plus.google.com/u/0/+EdoardoInamo'
github:         'https://github.com/kingsor'
twitter_name:	'@kingsor'

# Google Analytics
gahandler: 'UA-3163855-4'

# Disqus
disqushandler: false

# Blog Configurations
paginate: 5
destination: ./_site

# Custom vars
version:          0.8
